### ISSUE TITLE
Placeholder for title becomes editable when the user double clicks.

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#328]
## Bug Report

**Problematic behavior**
Here is a [video](https://www.loom.com/share/22c41836a9254727b0d024d761b2011f) of the problem.

**Comment by vinhyan** [comment]
Hi @virgile-dev! I'd like to give this a try please. :)

Thanks!

**Comment by vinhyan** [comment]
## Expected Behavior

For a document, the title in grey indicates that it is default placeholder text. If the title is in black, it means the title has been edited and updated successfully.  
To edit the title, click once on the placeholder text:

- If the title is not edited (or is blank), the default placeholder text remains.
- If the title is edited, the new title will be updated and displayed in black.

## Actual Behavior

Everything mentioned above works as expected; however, an issue arises if the following actions are performed quickly enough that the placeholder text remains instead of the textbox becoming empty for a new title:

1. Double-clicking to highlight the placeholder text.
2. Clicking and dragging the mouse to highlight the placeholder text, then stopping outside the textbox area.

In these cases, the user is allowed to add to the existing placeholder text (in grey). After clicking elsewhere on the page (or pressing Enter), the title is updated with a success toast notification. However, it remains grey (as if it's still a placeholder), instead of becoming black as expected for an edited title.

**Comment by vinhyan** [comment]
I'm also participating in Hacktoberfest 2024, it would be great if a `hacktoberfest` tag can be added to this issue. Thanks a lot! :)

**Comment by virgile-dev** [comment]
> I'm also participating in Hacktoberfest 2024, it would be great if a `hacktoberfest` tag can be added to this issue. Thanks a lot! :)

Hey @vinhyan make you sure you checkout https://github.com/TypeCellOS/BlockNote/issues
We rely on them for the editing experience and they have a lot of stuff you can contribute on.
I have a couple myself ^^ : https://github.com/TypeCellOS/BlockNote/issues/created_by/virgile-dev

**Comment by vinhyan** [comment]
Hi @virgile-dev! Thank you for the recommendation! I'll check them out for sure :).

Also, would you be able to add another label that is just "hacktoberfest", since the one added was not accepted for some reasons.

Thanks a lot! :)

**Comment by virgile-dev** [comment]
There you go @vinhyan !
