### ISSUE TITLE
Make toolbar / waffle configurable

### ISSUE THREAD

**Issue by rvveber** [numerique-gouv/impress#406]
## Feature Request

openDesk wants to have a universal Header to access any openDesk applications and Account settings from. 

Currently all applications integrated in openDesk need to implement it individually.

It should look like this:
![image](https://github.com/user-attachments/assets/c0d9997b-83d3-484e-8a6c-b3b30deb9f02)

The specification of what functionality needs to be implemented is currently beeing discussed and this issue will be updated later.

Anything that could benefit other users and contribute to the general whitelabeling of Docs, should go into the `main` branch.
All customization in regards to openDesk should go in the `main-opendesk` branch for now.
Maybe a Fork with openDesk customizations would make sense in the future.

**Comment by virgile-dev** [comment]
here is an example of how we did it : https://github.com/openfun/fun-richie-site-factory/tree/main/sites/ademe/src/frontend

**Comment by rvveber** [comment]
Thanks! Overriding a single component seems like flexible idea!

So after some more exploration it looks like we just need this app menu, next to the logo.
![image](https://github.com/user-attachments/assets/598819a5-8395-4f8d-9bb6-1e989f912fd3)

Since we can already change logo and colors via theming, i would wrap the docs title in a component
![image](https://github.com/user-attachments/assets/825a0925-6d49-4438-b437-f2d6b0ce36e5)
that we would replace in our deployment to be the app menu instead.

What do you think?

**Comment by rvveber** [comment]
@virgile-dev After looking into it a bit more, it is not as easy as i thought it was.

I could'nt find a way to override at runtime, like import a module only if it exists.

And we can't really override at build-time because kubernetes will use the image that is already built, compiled and without the source to build on.

**Comment by virgile-dev** [comment]
I really think we should do all these config at build time.
With Docs, we are not in the scenario of ZenDis working with an software editor, DINUM and ZenDis are the editors.
So I strongly recommend having a deploy repo or subrepo with all configs and overrides (the toolbar, i18n custom strings).
Especially since OpenDesk will be deployed by ZenDis to several clients with different requirements. We want Docs to remain generic so as many contributors as possible can join.
Happy to join in a call to discuss this whenever.
