### ISSUE TITLE
Document sometimes freezes when sync editing

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#440]
## Bug Report

**Problematic behavior**
This morning we were around 6 people on a doc a suddenly the document froze. We could move our cursors but couldn't edit it.
We didn't experience connectivity issues as we were all on a video conference.
After 5 min the document was editable again. Meanwhile we tried to refresh, log out, reload, nothing did the trick.
The 6 people on the call were using different browers : safari, firefox, chrome etc.
Most of us were at home on our personal computers so no weird setups involved eithers.

**Expected behavior/code**
The document shouldn't freeze.

**Comment by YousefED** [comment]
Do we have any pointers for this one yet / have we been able to reproduce this @AntoLC?

Because the editor really freezes, I almost think the issue must be somewhere on the front-end (but maybe triggered by a collaboration / sync issue)

I'm curious if we can reproduce this, and if so, whether we see any errors in the browser console. There's no sentry configured yet, right?

**Comment by AntoLC** [comment]
No errors at all, I have never seen this bug before, so my feeling is that it only happens when we are more than 3 or 4 on a document, I have the feeling that it is the hocus pocus server that has difficulty to do the doc updates.

I am digging in the issues that has faced hocus pocus.

I thought to add Redis as recommended:
https://tiptap.dev/docs/hocuspocus/guides/scalability

**Comment by YousefED** [comment]
I'm not convinced at this moment that it's hocuspocus / scaling related. Do we have any metrics about this / was there actually high load?

Also see this: https://tiptap.dev/docs/hocuspocus/server/extensions#redis:

> Please note that all messages will be handled on all instances of Hocuspocus, so if you are trying to reduce cpu load by spawning multiple servers, you should not connect them via Redis.

**Comment by AntoLC** [comment]
Yes I'm not convinced anymore that it is scalling related, I did some tests with about 30 simultaneously connections on a big doc, with videos, images, links, lot of headers, etc,  it was even amazingly smooth, my tests were on the production environment as well..

I'm adding logs on the collaborative server.
We still don't have too much metrics yet, so I think it is the next step.

**Comment by YousefED** [comment]
I doubt we'll see anything server side (unless there's a load issue). Sentry would be useful to see client-side errors!

**Comment by virgile-dev** [comment]
@AntoLC This bug is the one we had in the weekly call last week. There was 5 - 10 min where i couldn't make edits to the doc anymore.

**Comment by AntoLC** [comment]
I think I got it, we succeeded reproduce the case, I proposed a fix here:
https://github.com/yjs/y-prosemirror/issues/173

**Comment by AntoLC** [comment]
Thank you for your investigation, it is clear and nice.

I don't see too much how saving in a database could break the collaboration server though, because it is somehow totally isolated (client to django backend), a saving do not create rerender to the current client, neither to the other clients, when a new user arrives, even with an outdated document, it should sync with the others, am I wrong ? 

My 2 cents guess, if we are able to block the collaborative server with just a css property, I would not be surprise that an older version of a browser could create an issue in a very specific case (line moving/remove when a cursor is positioned in a specific type of block ?), we can see that older browsers have problems sometime.
I will try to improve the Sentry logs, I think it will popup by itself if it happen again.

**Comment by YousefED** [comment]
> I don't see too much how saving in a database could break the collaboration server though, because it is somehow totally isolated (client to django backend), a saving do not create rerender to the other clients, when a new user arrives, even with an outdated document, it should sync with the others, am I wrong?

You're right it should sync with others, my theory is there would be some kind of race condition between 3 kinds of datasources (Hocuspocus Awareness, Hocuspocus sync, S3 sync). In theory it should work afaik, but as it's an unconventional way I do think it's smart to keep our eyes open. Again, not able to reproduce, but good to keep in back of mind.

> older version of a browser could create an issue in a very specific case 

This is actually a really good point. I'll add this as "guess" to the analysis above

> I will try to improve the Sentry logs, I think it will popup by itself if it happen again.

Agree!

**Comment by dmonad** [comment]
Thanks @YousefED 

If I understand correctly, the issue happens when an exception is thrown in y-prosemirror's update handler.

Specifically the issue happens in `_typeChanged`, which is called by Yjs to update the ProseMirror state when a remote change happens).

This function should be able to handle everything you throw at it, as long as the change was generated by another y-prosemirror binding. 

I would like to debug the actual cause. Are there any real stack traces? It could be that some property is undefined in a weird edge-case. Just knowing which function throws the exception would help to debug the issue.

**Comment by YousefED** [comment]
> If I understand correctly, the issue happens when an exception is thrown in y-prosemirror's update handler.

> Specifically the issue happens in _typeChanged, which is called by Yjs to update the ProseMirror state when a remote change happens).

Correct

> I would like to debug the actual cause. Are there any real stack traces? It could be that some property is undefined in a weird edge-case. Just knowing which function throws the exception would help to debug the issue.

Unfortunately not, we installed Sentry only after we encountered the issue in prod. The only ways we've been able to reproduce it are listed above:
- `_isLocalCursorInView error` can happen when there's a specific CSS setup (see related issue linked above)
- `restoreRelativeSelection error` can happen when two documents have been (wrongly) initialized independently (see related issue linked above). Perhaps in other cases as well, but I think this has mostly been [fixed here](https://github.com/yjs/y-prosemirror/pull/171)

**Comment by dmonad** [comment]
> 
>     * `_isLocalCursorInView error` can happen when there's a specific CSS setup (see related issue linked above)
> 
>     * `restoreRelativeSelection error` can happen when two documents have been (wrongly) initialized independently (see related issue linked above). Perhaps in other cases as well, but I think this has mostly been [fixed here](https://github.com/yjs/y-prosemirror/pull/171)

There are (untested) fixes for both cases now. I suggest you consider this bug closed until you can reproduce it with the latest release of y-prosemirror. With the given information we can't do more.

**Comment by virgile-dev** [comment]
@AntoLC will we implement some of the fixes discussed here ? If yes we can close the issue when done.
